<a href="https://colab.research.google.com/github/emericericrainsds/rains/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projet d'étude 'rains' de la formation DataScienTest.com

accès public sur github:
[https://github.com/emericericrainsds/rains](https://github.com/emericericrainsds/rains)

le compte:   'emericericrainsds'

## Procedure pour contribuer à ce projet:

1.   Avoir un compte google
2.   Avoir un compte github lié à ce compte google
3.   Ajouter ce compte comme contributeur à 'emericericrainsds'
4.   'git cloner' le projet dans google drive
1.   Installer google drive for PC 
2.   Installer GitKraken et ouvrir 'emericericrainsds' depuis le google drive PC
1.   Utiliser 'Google colabs'

## 3. Ajouter ce compte comme contributeur à 'emericericrainsds'

*   se connecter sur [https://github.com/](https://github.com/)
compte google associé à 'emericericrainsds': 'emeric.eric.rains.ds@gmail.com'
mot de passe: 'Rains1_rains1'
*   Ajouter votre compte github comme collaborateur de 'rains': [https://github.com/emericericrainsds/rains/settings/access](https://github.com/emericericrainsds/rains/settings/access)
*   Vous recevrez un mail sur votre mail google pour valider la collaboration

## 4. 'git cloner' le projet dans google drive


*   depuis un navigateur ouvrir [google](https://google.com) et vous connecter à votre compte 
*   Ouvrir un onglet [google collabs](https://colab.research.google.com/?utm_source=scs-index#) et, si necéssaire, se connecter à son compte google
*   Dans le  [google drive](https://drive.google.com/drive/my-drive) creer un repertoire 'DataScienTest'
*   monter le google drive dans google collabs ...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

*   cloner le depot dans google drive

In [ ]:
# clone repo rains
%cd /content/drive/My\ Drive/DataScienTest/
!git clone https://github.com/emericericrainsds/rains

*   verifier le clone et creer une branche git perso

In [ ]:
%cd /content/drive/My\ Drive/DataScienTest/rains/
!git checkout #ma_branche_perso#
!git status

## 5 Installer google drive for PC
* [Drive pour ordinateur](https://www.google.com/intl/fr/drive/download/)

## 6 Installer et lancer GitKraken
*   [https://www.gitkraken.com/download](https://www.gitkraken.com/download)
*   Se connecter en utilisant votre compte google
*   Ouvrir le repository 'rains' ... 
1.   New Tab (Ctrl T)
2.   Open a repo
1.   Open a repository
2.   depuis l'explorateur de fichier chercher 'rains' dans le disque du 'google drive PC'(ie 'H:\Mon Drive\DataScienTest\rains')

## 7 Utiliser et tester 'Google Collabs'

*  Depuis un onglet 'Google collab' ou directement d'ici:

In [1]:
# mount dev.eengies google drive
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/DataScienTest/rains

Mounted at /content/drive
/content/drive/My Drive/DataScienTest/rains

In [2]:
import pandas as pd

df = pd.read_csv('input/rains.csv')
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Newcastle,13.2,NaN,0.0,NaN,NaN,NaN,NaN,NW,...,50.0,24.0,NaN,NaN,3.0,4.0,21.8,30.6,No,No
1,2008-12-02,Newcastle,NaN,32.2,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,59.0,NaN,NaN,NaN,0.0,NaN,25.4,No,No
2,2008-12-03,Newcastle,16.2,32.2,0.0,NaN,NaN,NaN,NaN,N,...,74.0,26.0,NaN,NaN,4.0,4.0,22.2,32.0,No,No
3,2008-12-04,Newcastle,19.2,24.0,0.0,NaN,NaN,NaN,NaN,SE,...,66.0,61.0,NaN,NaN,7.0,5.0,20.4,23.0,No,No
4,2008-12-05,Newcastle,18.8,30.2,0.0,NaN,NaN,NaN,NaN,NE,...,85.0,NaN,NaN,NaN,8.0,NaN,20.0,NaN,No,No